print("hello")
print('Hello')
print("We're going to the store")
print('He said "hi"')
print('we\'re going to the store')
print('Hi'+'there')
print('Hi','there')
print('Hi'+str(5))
print(int('8')+5)
print(float(8.5)+5)
